[metadata]
integration = ["windows", "linux"]

[rule]
author = ["lr2t9iz"]
index = [".fleet-agents-*"]
type = "query"
language = "kuery"
query = '''
NOT unenrolled_at:* AND 
last_checkin <= "now-15m" AND last_checkin >= "now-59m"
'''

name = "Elastic Agent Disconnected"
description = """
Detects when a SIEM agent stops sending logs for more than 15 minutes.
This could indicate connectivity issues, agent misconfigurations, or potential tampering.
"""
severity = "high"
risk_score = 89
tags = [ "OS: Windows", "OS: Linux" ]
references = [ "https://github.com/netero1010/EDRSilencer" ]
setup = """
check Fleet Agents (Status: Offline)
"""
note = """
Elastic Agent Disconnected
"""
max_signals = 100
rule_name_override = "local_metadata.host.hostname"
timestamp_override = "last_checkin"

from = "now-59m"
runs_every = 5m