[metadata]
creation_date = "2024/12/15"
integration = ["Elastic Agent"]
maturity = "production"
updated_date = "2024/12/23"

[rule]
author = ["lr2t9iz"]
index = [".fleet-agents-*"]
type = "query"
language = "kuery"
query = '''
NOT unenrolled_at:* AND 
last_checkin >= "now-59m" AND last_checkin <= "now-15m"
'''

name = "Elastic Agent Disconnected"
description = """
Detects when a SIEM agent stops sending logs for more than 15 minutes.
This could indicate connectivity issues, agent misconfigurations, or potential tampering.
"""
severity = "high"
risk_score = 89
tags = [ "OS: Windows", "OS: Linux" ]
references = [ "https://github.com/netero1010/EDRSilencer" ]
false_positives = [ "Network outages", "Agent intentionally disabled for maintenance" ]
setup = """## Setup
### Windows
```
Stop-Service Elastic Agent
Start-Service Elastic Agent
```
### Linux
```
sudo systemctl stop elastic-agent
sudo systemctl start elastic-agent

sudo service elastic-agent stop
sudo service elastic-agent start
```
"""
note = """## Triage and analysis
Check Fleet Agents (Status: Offline)
"""
max_signals = 100
rule_name_override = "local_metadata.host.hostname"
timestamp_override = "last_checkin"

from = "now-59m"
runs_every = "5m"